spring:
  datasource:
    url: jdbc:mysql://localhost:3306/driving_school?useSSL=false&serverTimezone=America/Santiago
    username: root # ← tu usuario
    password: "" # ← tu contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # validar/update/create-drop según tu entorno
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false

  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:a7f845d56d39c73c6c5b0d8cf9e46a67a7f845d56d39c73c6c5b0d8cf9e46a67}
    expiration-ms: 3600000 # 1 hora en milisegundos

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace
